### PR TITLE
Implement skeleton enemy character animations

### LINKED ISSUE #50: Implement skeleton enemy character animations
Enemy animations: https://github.com/FlamingoFiestaStudio/OlympusGoneWild/issues/8

Add animation to the project.

### PR DESCRIPTION
**Pull request by 201flaviosilva**
### Description

- Added the animations to the Enemy and implemented with the game flow;
- Flip enemy sprite based in the player position;

### Image/Video

https://github.com/FlamingoFiestaStudio/OlympusGoneWild/assets/55815265/46a54f8b-565e-4589-90db-210dfdd91843

(The enemy scale it's just for the video)

### Related Issue

Closes #50 

### Does this PR introduce a breaking change? ⚠️

- [X] No
- [ ] Yes

### Tests

- [X] I tested all game E2E;
- [ ] I just tested some scenes;
- [ ] Not applicable.

### Check list

Before submitting this pull request, please ensure the following are completed:

- [X] [My commits follow the project conventions](https://github.com/FlamingoFiestaStudio/OlympusGoneWild/wiki/ProjectBestPractices#commit-message-convections).
- [X] My code follows the project's coding style and conventions.
- [ ] I have updated the project documentation (if necessary).
- [ ] My code makes sense with the design.

## Additional Notes

N/A.

---

Thank you for your contribution to Olympus Gone Wild! Your effort is greatly appreciated, and it helps make this project better for everyone. 😄🎮🚀

### CODE REVIEW

**Review by Adan0k — COMMENTED** [review]
image
please, preload the player

**Comment by Adan0k** [comment]
image
some enemies aren't dying

**Comment by Gabriel-Sous-a** [comment]
Tested and the size of the enemies is not correct, the size is like it was before

**Comment by Gabriel-Sous-a** [comment]
There is a delay in the animation of the enemy getting hit the first time it gets hit

**Review by Gabriel-Sous-a — COMMENTED** [review]
Tested and the size of the enemies is not correct, the size is like it was before and there is a delay in the animation of the enemy getting hit the first time it gets hit

**Comment by 201flaviosilva** [comment]
This pull request was closed because the project was archived

**Pull request closed without merging**
